version: '3.9'
services:
  #node.js app
  app:
    image: yasg07/lab_neo4j
    container_name: neo4j_api
    ports:
      -  "3000:3000"
    environment:
      -  NEO4J_URI=neo4j://neo4jdb:7687
      -  REDIS_HOST=rediscachedb
      -  REDIS_PORT=6379
    depends_on:
      -  neo4jdb
      -  rediscachedb
    volumes:
      -  .:/usr/src/app
      -  /usr/src/app/node_modules
    command: npm start
  #Neo4j
  neo4jdb:
    image: neo4j
    container_name: neo4jdb
    ports:
      -  "7474:7474"
      -  "7687:7687"
    environment:
      -  NEO4J_AUTH=none
  #redis-cache-database
  rediscachedb:
    image: redis/redis-stack
    container_name: rediscachedb
    ports:
      -  "6379:6379"
      -  "8001:8001"